name: tests

on:
  push:
    paths:
      - src/**
      - src_rust/**
      - tests/**
      - Cargo.toml
      - pyproject.toml
      - .github/workflows/tests.yml

  pull_request:

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: [ '3.12', '3.13', '3.14' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        allow-prereleases: true

    - name: Install Maturin
      run: python3 -m pip install maturin

    - name: Install test dependencies
      run: |
        python3 -m pip install -U pip
        python3 -m pip install pytest

    - name: Install Unix dependencies
      if: matrix.os != 'windows-latest'
      run: python3 -m pip install pytest-forked

    - name: Build and install SlipCover
      run: |
        maturin develop --release

    - name: Run tests
      run: python3 -m pytest

  # Test building from source distribution
  test-build-from-source:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.12', '3.13', '3.14']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          allow-prereleases: true

      - name: Install build dependencies
        run: |
          python3 -m pip install -U pip
          python3 -m pip install maturin build

      - name: Build sdist
        run: python3 -m build --sdist

      - name: Test building from sdist
        run: |
          tar xzf dist/slipcover*.tar.gz
          cd slipcover*
          python3 -m pip install maturin
          python3 -m build --wheel
